In [22]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split


def loader(fname):
    record = np.load(fname, allow_pickle=True)
    return record['X'], record['y']


def test(clf, fname='test0.npz'):
    X_test, y_test = loader('test.npz') 
    y_predict = clf.predict(X_test)
    a = accuracy_score(y_test, y_predict)
    print(f'accuracy = {a:.2%}')



X, y = loader('train.npz')

clf = KNeighborsClassifier(n_neighbors=9)
clf.fit(X, y)
print()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

test(clf)



accuracy = 90.91%


In [45]:
from sklearn.model_selection import KFold


n_neighbors_test = 20

from collections import defaultdict

result = defaultdict(lambda: [])

n_split = 5
def cv(dataset):
    for i in range(1, n_split - 1):
        start = (i) * int(len(dataset) / n_split)
        end = (i + 1) * int(len(dataset) / n_split)
        yield dataset[start:end]
start = 0
end = int(len(X) / n_split)
reference_portion, test_portion = X[start:end], X[end:]

for parameter in (1, n_neighbors_test, 2):
    for d in cv(test_portion):
        
        clf = KNeighborsClassifier(n_neighbors=9)
        print(d)
# Tutaj nie patrz to jest worthless nie rozumiałem co mamy wgl zrobić nie mam takiego dużego okna kontekstowego w głowie

[[15.1 22.02 97.26 ... 0.153 0.2675 0.07873]
 [15.5 21.08 102.9 ... 0.2134 0.3003 0.1048]
 [15.66 23.2 110.2 ... 0.2462 0.3277 0.1019]
 ...
 [7.691 25.44 48.34 ... 0.05 0.279 0.1066]
 [11.69 24.44 76.37 ... 0.1308 0.2803 0.0997]
 [17.05 19.08 113.4 ... 0.2543 0.3109 0.09061]]
[[11.71 15.45 75.03 ... 0.07864 0.2765 0.07806]
 [12.07 13.44 77.83 ... 0.07393 0.2781 0.08052]
 [12.19 13.29 79.08 ... 0.08187 0.3469 0.09241]
 ...
 [15.75 19.22 107.1 ... 0.2135 0.4245 0.105]
 [12.45 15.7 82.57 ... 0.1741 0.3985 0.1244]
 [24.25 20.2 166.2 ... 0.2248 0.3222 0.08009]]
[[21.09 26.57 142.7 ... 0.2903 0.4098 0.1284]
 [13.7 17.64 87.76 ... 0.09077 0.2518 0.0696]
 [13.59 17.84 86.24 ... 0.05185 0.2335 0.06263]
 ...
 [13.85 15.18 88.99 ... 0.09993 0.2955 0.06912]
 [11.93 10.91 76.14 ... 0.06876 0.246 0.07262]
 [11.94 20.76 77.87 ... 0.1155 0.2465 0.09981]]
[[15.1 22.02 97.26 ... 0.153 0.2675 0.07873]
 [15.5 21.08 102.9 ... 0.2134 0.3003 0.1048]
 [15.66 23.2 110.2 ... 0.2462 0.3277 0.1019]
 ...
 [7.691 2